function _jsInclude(path){
  document.write('<script src="' + path + '?' + version + '"></script>')
}
_jsInclude("js/Piece.js")
_jsInclude("js/Movement.js")
_jsInclude("js/DobutsuMovement.js")
_jsInclude("js/Position.js")
_jsInclude("js/GameTimer.js")
_jsInclude("js/SoundPlayer.js")
_jsInclude("js/Board.js")
_jsInclude("js/DobutsuBoard.js")
_jsInclude("js/BoardArrow.js")
_jsInclude("js/Country.js")
_jsInclude("js/User.js")
_jsInclude("js/Game.js")
_jsInclude("js/Tournament.js")
_jsInclude("js/WebSocketClient.js")
_jsInclude("js/WebSystemApiClient.js")
_jsInclude("js/WorldClock.js")
_jsInclude("js/util.js")
_jsInclude("js/main.js")
